steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'northamerica-northeast1-docker.pkg.dev/global-env-365718/repo-docker-ycng/ycng_image_predictor', '.' ] 
images: ['northamerica-northeast1-docker.pkg.dev/global-env-365718/repo-docker-ycng/ycng_image_predictor']

timeout: '1200s'
