steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'global (non-regional)-docker.pkg.dev/global-env-365718/ycng228/ycng_image_predictor', '.' ]
images: ['global (non-regional)-docker.pkg.dev/global-env-365718/ycng228/ycng_image_predictor']

timeout: '1200s'
